version: "3.9"

services:
  server:
    build: /
    container_name: server
    ports:
      - '8080:8080'
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'todo'
    ports:
      - '3306:3306'
    command: --init-file /data/application/init.sql
    volumes:
      - ./src/main/resources/init.sql:/data/application/init.sql
      - my-db:/var/lib/mysql

volumes:
  my-db:
